branch-defaults:
  master:
    environment: frsh1-dev
global:
  application_name: frsh1
  default_ec2_keyname: frsh
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
